public class Pokedex {
  
        static String[][] pokedex = {
                { "national_number", "gen", "english_name", "japanese_name", "primary_type", "secondary_type",
                        "classification", "percent_male", "percent_female", "height_m", "weight_kg", "capture_rate",
                        "base_egg_steps", "hp", "attack", "defense", "sp_attack", "sp_defense", "speed", "abilities_0",
                        "abilities_1", "abilities_2", "abilities_hidden", "against_normal", "against_fire", "against_water",
                        "against_electric", "against_grass", "against_ice", "against_fighting", "against_poison",
                        "against_ground", "against_flying", "against_psychic", "against_bug", "against_rock",
                        "against_ghost", "against_dragon", "against_dark", "against_steel", "against_fairy",
                        "is_sublegendary", "is_legendary", "is_mythical", "evochain_0", "evochain_1", "evochain_2",
                        "evochain_3", "evochain_4", "evochain_5", "evochain_6", "gigantamax", "mega_evolution",
                        "mega_evolution_alt", "description" },
                { "1", "I", "Bulbasaur", "Fushigidane", "grass", "poison", "Seed Pokémon", "88.14", "11.86", "0.7", "6.9",
                        "45", "5120", "45", "49", "49", "65", "65", "45", "Overgrow", "", "", "Chlorophyll", "1", "2",
                        "0.5", "0.5", "0.25", "2", "0.5", "1", "1", "2", "2", "1", "1", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Bulbasaur", "Level ", "Ivysaur", "Level ", "Venusaur", "", "", "", "", "",
                        "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger." },
                { "2", "I", "Ivysaur", "Fushigisou", "grass", "poison", "Seed Pokémon", "88.14", "11.86", "1", "13", "45",
                        "5120", "60", "62", "63", "80", "80", "60", "Overgrow", "", "", "Chlorophyll", "1", "2", "0.5",
                        "0.5", "0.25", "2", "0.5", "1", "1", "2", "2", "1", "1", "1", "1", "1", "1", "0.5", "0", "0", "0",
                        "Bulbasaur", "Level ", "Ivysaur", "Level ", "Venusaur", "", "", "", "", "",
                        "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs." },
                { "3", "I", "Venusaur", "Fushigibana", "grass", "poison", "Seed Pokémon", "88.14", "11.86", "2", "100",
                        "45", "5120", "80", "82", "83", "100", "100", "80", "Overgrow", "", "", "Chlorophyll", "1", "2",
                        "0.5", "0.5", "0.25", "2", "0.5", "1", "1", "2", "2", "1", "1", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Bulbasaur", "Level ", "Ivysaur", "Level ", "Venusaur", "", "", "Gigantamax Venusaur",
                        "Mega Venusaur", "",
                        "Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight." },
                { "4", "I", "Charmander", "Hitokage", "fire", "", "Lizard Pokémon", "88.14", "11.86", "0.6", "8.5", "45",
                        "5120", "39", "52", "43", "60", "50", "65", "Blaze", "", "", "Solar Power", "1", "0.5", "2", "1",
                        "0.5", "0.5", "1", "1", "2", "1", "1", "0.5", "2", "1", "1", "1", "0.5", "0.5", "0", "0", "0",
                        "Charmander", "Level ", "Charmeleon", "Level ", "Charizard", "", "", "", "", "",
                        "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail." },
                { "5", "I", "Charmeleon", "Lizardo", "fire", "", "Flame Pokémon", "88.14", "11.86", "1.1", "19", "45",
                        "5120", "58", "64", "58", "80", "65", "80", "Blaze", "", "", "Solar Power", "1", "0.5", "2", "1",
                        "0.5", "0.5", "1", "1", "2", "1", "1", "0.5", "2", "1", "1", "1", "0.5", "0.5", "0", "0", "0",
                        "Charmander", "Level ", "Charmeleon", "Level ", "Charizard", "", "", "", "", "",
                        "It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws." },
                { "6", "I", "Charizard", "Lizardon", "fire", "flying", "Flame Pokémon", "88.14", "11.86", "1.7", "90.5",
                        "45", "5120", "78", "84", "78", "109", "85", "100", "Blaze", "", "", "Solar Power", "1", "0.5", "2",
                        "2", "0.25", "1", "0.5", "1", "0", "1", "1", "0.25", "4", "1", "1", "1", "0.5", "0.5", "0", "0",
                        "0", "Charmander", "Level ", "Charmeleon", "Level ", "Charizard", "", "", "Gigantamax Charizard",
                        "Mega Charizard X", "Mega Charizard Y",
                        "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames." },
                { "7", "I", "Squirtle", "Zenigame", "water", "", "Tiny Turtle Pokémon", "88.14", "11.86", "0.5", "9", "45",
                        "5120", "44", "48", "65", "50", "64", "43", "Torrent", "", "", "Rain Dish", "1", "0.5", "0.5", "2",
                        "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0", "Squirtle",
                        "Level ", "Wartortle", "Level ", "Blastoise", "", "", "", "", "",
                        "When it retracts its long neck into its shell, it squirts out water with vigorous force." },
                { "8", "I", "Wartortle", "Kameil", "water", "", "Turtle Pokémon", "88.14", "11.86", "1", "22.5", "45",
                        "5120", "59", "63", "80", "65", "80", "58", "Torrent", "", "", "Rain Dish", "1", "0.5", "0.5", "2",
                        "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0", "Squirtle",
                        "Level ", "Wartortle", "Level ", "Blastoise", "", "", "", "", "",
                        "It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old." },
                { "9", "I", "Blastoise", "Kamex", "water", "", "Shellfish Pokémon", "88.14", "11.86", "1.6", "85.5", "45",
                        "5120", "79", "83", "100", "85", "105", "78", "Torrent", "", "", "Rain Dish", "1", "0.5", "0.5",
                        "2", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0",
                        "Squirtle", "Level ", "Wartortle", "Level ", "Blastoise", "", "", "Gigantamax Blastoise",
                        "Mega Blastoise", "",
                        "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell." },
                { "10", "I", "Caterpie", "Caterpie", "bug", "", "Worm Pokémon", "50.2", "49.8", "0.3", "2.9", "255", "3840",
                        "45", "30", "35", "20", "20", "45", "Shield Dust", "", "", "Run Away", "1", "2", "1", "1", "0.5",
                        "1", "0.5", "1", "0.5", "2", "1", "1", "2", "1", "1", "1", "1", "1", "0", "0", "0", "Caterpie",
                        "Level ", "Metapod", "Level ", "Butterfree", "", "", "", "", "",
                        "For protection, it releases a horrible stench from the antenna on its head to drive away enemies." },
                { "11", "I", "Metapod", "Transel", "bug", "", "Cocoon Pokémon", "50.2", "49.8", "0.7", "9.9", "120", "3840",
                        "50", "20", "55", "25", "25", "30", "Shed Skin", "", "", "", "1", "2", "1", "1", "0.5", "1", "0.5",
                        "1", "0.5", "2", "1", "1", "2", "1", "1", "1", "1", "1", "0", "0", "0", "Caterpie", "Level ",
                        "Metapod", "Level ", "Butterfree", "", "", "", "", "",
                        "It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless to avoid attack." },
                { "12", "I", "Butterfree", "Butterfree", "bug", "flying", "Butterfly Pokémon", "50.2", "49.8", "1.1", "32",
                        "45", "3840", "60", "45", "50", "90", "80", "70", "Compoundeyes", "", "", "Tinted Lens", "1", "2",
                        "1", "2", "0.25", "2", "0.25", "1", "0", "2", "1", "0.5", "4", "1", "1", "1", "1", "1", "0", "0",
                        "0", "Caterpie", "Level ", "Metapod", "Level ", "Butterfree", "", "", "Gigantamax Butterfree", "",
                        "", "In battle, it flaps its wings at great speed to release highly toxic dust into the air." },
                { "13", "I", "Weedle", "Beedle", "bug", "poison", "Hairy Pokémon", "50", "50", "0.3", "3.2", "255", "3840",
                        "40", "35", "30", "20", "20", "50", "Shield Dust", "", "", "Run Away", "1", "2", "1", "1", "0.25",
                        "1", "0.25", "0.5", "1", "2", "2", "0.5", "2", "1", "1", "1", "1", "0.5", "0", "0", "0", "Weedle",
                        "Level ", "Kakuna", "Level ", "Beedrill", "", "", "", "", "",
                        "Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves." },
                { "14", "I", "Kakuna", "Cocoon", "bug", "poison", "Cocoon Pokémon", "50", "50", "0.6", "10", "120", "3840",
                        "45", "25", "50", "25", "25", "35", "Shed Skin", "", "", "", "1", "2", "1", "1", "0.25", "1",
                        "0.25", "0.5", "1", "2", "2", "0.5", "2", "1", "1", "1", "1", "0.5", "0", "0", "0", "Weedle",
                        "Level ", "Kakuna", "Level ", "Beedrill", "", "", "", "", "",
                        "Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy." },
                { "15", "I", "Beedrill", "Spear", "bug", "poison", "Poison Bee Pokémon", "50", "50", "1", "29.5", "45",
                        "3840", "65", "90", "40", "45", "80", "75", "Swarm", "", "", "Sniper", "1", "2", "1", "1", "0.25",
                        "1", "0.25", "0.5", "1", "2", "2", "0.5", "2", "1", "1", "1", "1", "0.5", "0", "0", "0", "Weedle",
                        "Level ", "Kakuna", "Level ", "Beedrill", "", "", "", "Mega Beedrill", "",
                        "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly." },
                { "16", "I", "Pidgey", "Poppo", "normal", "flying", "Tiny Bird Pokémon", "50", "50", "0.3", "1.8", "255",
                        "3840", "40", "45", "40", "35", "35", "56", "Keen Eye", "Tangled Feet", "", "Big Pecks", "1", "1",
                        "1", "2", "0.5", "2", "1", "1", "0", "1", "1", "0.5", "2", "0", "1", "1", "1", "1", "0", "0", "0",
                        "Pidgey", "Level ", "Pidgeotto", "Level ", "Pidgeot", "", "", "", "", "",
                        "Very docile. If attacked, it will often kick up sand to protect itself rather than fight back." },
                { "17", "I", "Pidgeotto", "Pigeon", "normal", "flying", "Bird Pokémon", "50", "50", "1.1", "30", "120",
                        "3840", "63", "60", "55", "50", "50", "71", "Keen Eye", "Tangled Feet", "", "Big Pecks", "1", "1",
                        "1", "2", "0.5", "2", "1", "1", "0", "1", "1", "0.5", "2", "0", "1", "1", "1", "1", "0", "0", "0",
                        "Pidgey", "Level ", "Pidgeotto", "Level ", "Pidgeot", "", "", "", "", "",
                        "This Pokémon is full of vitality. It constantly flies around its large territory in search of prey." },
                { "18", "I", "Pidgeot", "Pigeot", "normal", "flying", "Bird Pokémon", "50", "50", "1.5", "39.5", "45",
                        "3840", "83", "80", "75", "70", "70", "101", "Keen Eye", "Tangled Feet", "", "Big Pecks", "1", "1",
                        "1", "2", "0.5", "2", "1", "1", "0", "1", "1", "0.5", "2", "0", "1", "1", "1", "1", "0", "0", "0",
                        "Pidgey", "Level ", "Pidgeotto", "Level ", "Pidgeot", "", "", "", "Mega Pidgeot", "",
                        "This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons." },
                { "19", "I", "Rattata", "Koratta", "normal", "dark", "Mouse Pokémon", "50", "50", "0.3", "3.5", "255",
                        "3840", "30", "56", "35", "25", "35", "72", "Run Away", "Guts", "", "Hustle", "1", "1", "1", "1",
                        "1", "1", "2", "1", "1", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "0", "0", "Rattata",
                        "Level", "Raticate", "", "", "", "", "", "", "",
                        "Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area." },
                { "20", "I", "Raticate", "Ratta", "normal", "dark", "Mouse Pokémon", "50", "50", "0.7", "18.5", "127",
                        "3840", "55", "81", "60", "50", "70", "97", "Run Away", "Guts", "", "Hustle", "1", "1", "1", "1",
                        "1", "1", "2", "1", "1", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "0", "0", "Rattata",
                        "Level", "Raticate", "", "", "", "", "", "", "",
                        "Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey." },
                { "21", "I", "Spearow", "Onisuzume", "normal", "flying", "Tiny Bird Pokémon", "50", "50", "0.3", "2", "255",
                        "3840", "40", "60", "30", "31", "31", "70", "Keen Eye", "", "", "Sniper", "1", "1", "1", "2", "0.5",
                        "2", "1", "1", "0", "1", "1", "0.5", "2", "0", "1", "1", "1", "1", "0", "0", "0", "Spearow",
                        "Level ", "Fearow", "", "", "", "", "", "", "",
                        "Inept at flying high. However, it can fly around very fast to protect its territory." },
                { "22", "I", "Fearow", "Onidrill", "normal", "flying", "Beak Pokémon", "50", "50", "1.2", "38", "90",
                        "3840", "65", "90", "65", "61", "61", "100", "Keen Eye", "", "", "Sniper", "1", "1", "1", "2",
                        "0.5", "2", "1", "1", "0", "1", "1", "0.5", "2", "0", "1", "1", "1", "1", "0", "0", "0", "Spearow",
                        "Level ", "Fearow", "", "", "", "", "", "", "",
                        "A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly." },
                { "23", "I", "Ekans", "Arbo", "poison", "", "Snake Pokémon", "50", "50", "2", "6.9", "255", "5120", "35",
                        "60", "44", "40", "54", "55", "Intimidate", "Shed Skin", "", "Unnerve", "1", "1", "1", "1", "0.5",
                        "1", "0.5", "0.5", "2", "1", "2", "0.5", "1", "1", "1", "1", "1", "0.5", "0", "0", "0", "Ekans",
                        "Level ", "Arbok", "", "", "", "", "", "", "",
                        "The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest." },
                { "24", "I", "Arbok", "Arbok", "poison", "", "Cobra Pokémon", "50", "50", "3.5", "65", "90", "5120", "60",
                        "95", "69", "65", "79", "80", "Intimidate", "Shed Skin", "", "Unnerve", "1", "1", "1", "1", "0.5",
                        "1", "0.5", "0.5", "2", "1", "2", "0.5", "1", "1", "1", "1", "1", "0.5", "0", "0", "0", "Ekans",
                        "Level ", "Arbok", "", "", "", "", "", "", "",
                        "The frightening patterns on its belly have been studied. Six variations have been confirmed." },
                { "25", "I", "Pikachu", "Pikachu", "electric", "", "Mouse Pokémon", "50.2", "49.8", "0.4", "6", "190",
                        "2560", "35", "55", "40", "50", "50", "90", "Static", "", "", "Lightning Rod", "1", "1", "1", "0.5",
                        "1", "1", "1", "1", "2", "0.5", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0", "Pichu",
                        "Level Up with Happiness Value at 220", "Pikachu", "Use Thunder Stone", "Raichu", "", "",
                        "Gigantamax Pikachu", "", "",
                        "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy." },
                { "26", "I", "Raichu", "Raichu", "electric", "electric", "Mouse Pokémon", "50.2", "49.8", "0.8", "30", "75",
                        "2560", "60", "90", "55", "90", "80", "110", "Static", "Surge Surfer (Alola Form)", "",
                        "Lightning Rod", "1", "1", "1", "0.5", "1", "1", "1", "1", "2", "0.5", "1", "1", "1", "1", "1", "1",
                        "0.5", "1", "0", "0", "0", "Pichu", "Level Up with Happiness Value at 220", "Pikachu",
                        "Use Thunder Stone", "Raichu", "", "", "", "", "",
                        "Its long tail serves as a ground to protect itself from its own high-voltage power." },
                { "27", "I", "Sandshrew", "Sand", "ground", "ice", "Mouse Pokémon", "50.2", "49.8", "0.6", "12", "255",
                        "5120", "50", "75", "85", "20", "30", "40", "Sand Veil", "", "", "Snow Cloak- Slush Rush", "1", "1",
                        "2", "0", "2", "2", "1", "0.5", "1", "1", "1", "1", "0.5", "1", "1", "1", "1", "1", "0", "0", "0",
                        "Sandshrew", "Level", "Sandslash", "", "", "", "", "", "", "",
                        "It loves to bathe in the grit of dry, sandy areas. By sand bathing, the Pokémon rids itself of dirt and moisture clinging to its body." },
                { "28", "I", "Sandslash", "Sandpan", "ground", "ice", "Mouse Pokémon", "50.2", "49.8", "1", "29.5", "90",
                        "5120", "75", "100", "110", "45", "55", "65", "Sand Veil", "", "", "Snow Cloak- Slush Rush", "1",
                        "1", "2", "0", "2", "2", "1", "0.5", "1", "1", "1", "1", "0.5", "1", "1", "1", "1", "1", "0", "0",
                        "0", "Sandshrew", "Level", "Sandslash", "", "", "", "", "", "", "",
                        "The drier the area Sandslash lives in, the harder and smoother the Pokémon’s spikes will feel when touched." },
                { "29", "I", "Nidoran♀", "Nidoran♀", "poison", "", "Poison Pin Pokémon", "0", "100", "0.4", "7", "235",
                        "5120", "55", "47", "52", "40", "40", "41", "Poison Point", "Rivalry", "", "Hustle", "1", "1", "1",
                        "1", "0.5", "1", "0.5", "0.5", "2", "1", "2", "0.5", "1", "1", "1", "1", "1", "0.5", "0", "0", "0",
                        "Egg", "When Female", "Nidoran♀", "Level 16", "Nidorina", "Use Moonstone", "Nidoqueen", "", "", "",
                        "Females are more sensitive to smells than males. While foraging, they’ll use their whiskers to check wind direction and stay downwind of predators." },
                { "30", "I", "Nidorina", "Nidorina", "poison", "", "Poison Pin Pokémon", "0", "100", "0.8", "20", "120",
                        "5120", "70", "62", "67", "55", "55", "56", "Poison Point", "Rivalry", "", "Hustle", "1", "1", "1",
                        "1", "0.5", "1", "0.5", "0.5", "2", "1", "2", "0.5", "1", "1", "1", "1", "1", "0.5", "0", "0", "0",
                        "Egg", "When Female", "Nidoran♀", "Level 16", "Nidorina", "Use Moonstone", "Nidoqueen", "", "", "",
                        "The horn on its head has atrophied. It’s thought that this happens so Nidorina’s children won’t get poked while their mother is feeding them." },
                { "31", "I", "Nidoqueen", "Nidoqueen", "poison", "ground", "Drill Pokémon", "0", "100", "1.3", "60", "45",
                        "5120", "90", "92", "87", "75", "85", "76", "Poison Point", "Rivalry", "", "Sheer Force", "1", "1",
                        "2", "0", "1", "2", "0.5", "0.25", "2", "1", "2", "0.5", "0.5", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Egg", "When Female", "Nidoran♀", "Level 16", "Nidorina", "Use Moonstone", "Nidoqueen", "", "",
                        "",
                        "Nidoqueen is better at defense than offense. With scales like armor, this Pokémon will shield its children from any kind of attack." },
                { "32", "I", "Nidoran♂", "Nidoran♂", "poison", "", "Poison Pin Pokémon", "100", "0", "0.5", "9", "235",
                        "5120", "46", "57", "40", "40", "40", "50", "Poison Point", "Rivalry", "", "Hustle", "1", "1", "1",
                        "1", "0.5", "1", "0.5", "0.5", "2", "1", "2", "0.5", "1", "1", "1", "1", "1", "0.5", "0", "0", "0",
                        "Egg", "When Male", "Nidoran♂", "Level 16", "Nidorino", "Use Moonstone", "Nidoking", "", "", "",
                        "The horn on a male Nidoran’s forehead contains a powerful poison. This is a very cautious Pokémon, always straining its large ears." },
                { "33", "I", "Nidorino", "Nidorino", "poison", "", "Poison Pin Pokémon", "100", "0", "0.9", "19.5", "120",
                        "5120", "61", "72", "57", "55", "55", "65", "Poison Point", "Rivalry", "", "Hustle", "1", "1", "1",
                        "1", "0.5", "1", "0.5", "0.5", "2", "1", "2", "0.5", "1", "1", "1", "1", "1", "0.5", "0", "0", "0",
                        "Egg", "When Male", "Nidoran♂", "Level 16", "Nidorino", "Use Moonstone", "Nidoking", "", "", "",
                        "With a horn that’s harder than diamond, this Pokémon goes around shattering boulders as it searches for a moon stone." },
                { "34", "I", "Nidoking", "Nidoking", "poison", "ground", "Drill Pokémon", "100", "0", "1.4", "62", "45",
                        "5120", "81", "102", "77", "85", "75", "85", "Poison Point", "Rivalry", "", "Sheer Force", "1", "1",
                        "2", "0", "1", "2", "0.5", "0.25", "2", "1", "2", "0.5", "0.5", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Egg", "When Male", "Nidoran♂", "Level 16", "Nidorino", "Use Moonstone", "Nidoking", "", "",
                        "",
                        "When it goes on a rampage, it’s impossible to control. But in the presence of a Nidoqueen it’s lived with for a long time, Nidoking calms down." },
                { "35", "I", "Clefairy", "Pippi", "fairy", "", "Fairy Pokémon", "24.9", "75.1", "0.6", "7.5", "150", "2560",
                        "70", "45", "48", "60", "65", "35", "Cute Charm", "Magic Guard", "", "Friend Guard", "1", "1", "1",
                        "1", "1", "1", "0.5", "2", "1", "1", "1", "0.5", "1", "1", "0", "0.5", "2", "1", "0", "0", "0",
                        "Cleffa", "Level Up with Happiness Value at 220", "Clefairy", "Use Moon Stone", "Clefable", "", "",
                        "", "", "",
                        "It is said that happiness will come to those who see a gathering of Clefairy dancing under a full moon." },
                { "36", "I", "Clefable", "Pixy", "fairy", "", "Fairy Pokémon", "24.9", "75.1", "1.3", "40", "25", "2560",
                        "95", "70", "73", "95", "90", "60", "Cute Charm", "Magic Guard", "", "Unaware", "1", "1", "1", "1",
                        "1", "1", "0.5", "2", "1", "1", "1", "0.5", "1", "1", "0", "0.5", "2", "1", "0", "0", "0", "Cleffa",
                        "Level Up with Happiness Value at 220", "Clefairy", "Use Moon Stone", "Clefable", "", "", "", "",
                        "",
                        "A timid fairy Pokémon that is rarely seen, it will run and hide the moment it senses people." },
                { "37", "I", "Vulpix", "Rokon", "fire", "ice", "Fox Pokémon", "24.9", "75.1", "0.6", "9.9", "190", "5120",
                        "38", "41", "40", "50", "65", "65", "Flash Fire", "", "", "Snow Cloak- Snow Warning", "1", "0.5",
                        "2", "1", "0.5", "0.5", "1", "1", "2", "1", "1", "0.5", "2", "1", "1", "1", "0.5", "0.5", "0", "0",
                        "0", "Vulpix", "Use Fire Stone", "Ninetales", "", "", "", "", "", "", "",
                        "While young, it has six gorgeous tails. When it grows, several new tails are sprouted." },
                { "38", "I", "Ninetales", "Kyukon", "fire", "ice", "Fox Pokémon", "24.9", "75.1", "1.1", "19.9", "75",
                        "5120", "73", "76", "75", "81", "100", "100", "Flash Fire", "", "", "Snow Cloak- Snow Warning", "1",
                        "0.5", "2", "1", "0.5", "0.5", "1", "1", "2", "1", "1", "0.5", "2", "1", "1", "1", "0.5", "0.5",
                        "0", "0", "0", "Vulpix", "Use Fire Stone", "Ninetales", "", "", "", "", "", "", "",
                        "It is said to live 1,000 years, and each of its tails is loaded with supernatural powers." },
                { "39", "I", "Jigglypuff", "Purin", "normal", "fairy", "Balloon Pokémon", "24.9", "75.1", "0.5", "5.5",
                        "170", "2560", "115", "45", "20", "45", "25", "20", "Cute Charm", "Competitive", "", "Friend Guard",
                        "1", "1", "1", "1", "1", "1", "1", "2", "1", "1", "1", "0.5", "1", "0", "0", "0.5", "2", "1", "0",
                        "0", "0", "Igglybuff", "Level Up with Happiness Value at 220", "Jigglypuff", "Use Moon Stone",
                        "Wigglytuff", "", "", "", "", "",
                        "Jigglypuff has top-notch lung capacity, even by comparison to other Pokémon. It won’t stop singing its lullabies until its foes fall asleep." },
                { "40", "I", "Wigglytuff", "Pukurin", "normal", "fairy", "Balloon Pokémon", "24.9", "75.1", "1", "12", "50",
                        "2560", "140", "70", "45", "85", "50", "45", "Cute Charm", "Competitive", "", "Frisk", "1", "1",
                        "1", "1", "1", "1", "1", "2", "1", "1", "1", "0.5", "1", "0", "0", "0.5", "2", "1", "0", "0", "0",
                        "Igglybuff", "Level Up with Happiness Value at 220", "Jigglypuff", "Use Moon Stone", "Wigglytuff",
                        "", "", "", "", "",
                        "The more air it takes in, the more it inflates. If opponents catch it in a bad mood, it will inflate itself to an enormous size to intimidate them." },
                { "41", "I", "Zubat", "Zubat", "poison", "flying", "Bat Pokémon", "50.2", "49.8", "0.8", "7.5", "255",
                        "3840", "40", "45", "35", "30", "40", "55", "Inner Focus", "", "", "Infiltrator", "1", "1", "1",
                        "2", "0.25", "2", "0.25", "0.5", "0", "1", "2", "0.25", "2", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Zubat", "Level ", "Golbat", "Level Up with Happiness Value at 220", "Crobat", "", "", "", "",
                        "",
                        "It emits ultrasonic waves from its mouth to check its surroundings. Even in tight caves, Zubat flies around with skill." },
                { "42", "I", "Golbat", "Golbat", "poison", "flying", "Bat Pokémon", "50.2", "49.8", "1.6", "55", "90",
                        "3840", "75", "80", "70", "65", "75", "90", "Inner Focus", "", "", "Infiltrator", "1", "1", "1",
                        "2", "0.25", "2", "0.25", "0.5", "0", "1", "2", "0.25", "2", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Zubat", "Level ", "Golbat", "Level Up with Happiness Value at 220", "Crobat", "", "", "", "",
                        "",
                        "It loves to drink other creatures’ blood. It’s said that if it finds others of its kind going hungry, it sometimes shares the blood it’s gathered." },
                { "43", "I", "Oddish", "Nazonokusa", "grass", "poison", "Weed Pokémon", "50.2", "49.8", "0.5", "5.4", "255",
                        "5120", "45", "50", "55", "75", "65", "30", "Chlorophyll", "", "", "Run Away", "1", "2", "0.5",
                        "0.5", "0.25", "2", "0.5", "1", "1", "2", "2", "1", "1", "1", "1", "1", "1", "0.5", "0", "0", "0",
                        "Oddish", "Level", "Gloom", "Use Leaf Stone", "Vileplume", "Use Sun Stone", "Bellossom", "", "", "",
                        "If exposed to moonlight, it starts to move. It roams far and wide at night to scatter its seeds." },
                { "44", "I", "Gloom", "Kusaihana", "grass", "poison", "Weed Pokémon", "50.2", "49.8", "0.8", "8.6", "120",
                        "5120", "60", "65", "70", "85", "75", "40", "Chlorophyll", "", "", "Stench", "1", "2", "0.5", "0.5",
                        "0.25", "2", "0.5", "1", "1", "2", "2", "1", "1", "1", "1", "1", "1", "0.5", "0", "0", "0",
                        "Oddish", "Level", "Gloom", "Use Leaf Stone", "Vileplume", "Use Sun Stone", "Bellossom", "", "", "",
                        "Its pistils exude an incredibly foul odor. The horrid stench can cause fainting at a distance of 1.25 miles." },
                { "45", "I", "Vileplume", "Ruffresia", "grass", "poison", "Flower Pokémon", "50.2", "49.8", "1.2", "18.6",
                        "45", "5120", "75", "80", "85", "110", "90", "50", "Chlorophyll", "", "", "Effect Spore", "1", "2",
                        "0.5", "0.5", "0.25", "2", "0.5", "1", "1", "2", "2", "1", "1", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Oddish", "Level", "Gloom", "Use Leaf Stone", "Vileplume", "", "", "", "", "",
                        "It has the world’s largest petals. With every step, the petals shake out heavy clouds of toxic pollen." },
                { "46", "I", "Paras", "Paras", "bug", "grass", "Mushroom Pokémon", "50", "50", "0.3", "5.4", "190", "5120",
                        "35", "70", "55", "45", "55", "25", "Effect Spore", "Dry Skin", "", "Damp", "1", "4", "0.5", "0.5",
                        "0.25", "2", "0.5", "2", "0.25", "4", "1", "2", "2", "1", "1", "1", "1", "1", "0", "0", "0",
                        "Paras", "Level ", "Parasect", "", "", "", "", "", "", "",
                        "Burrows under the ground to gnaw on tree roots. The mushrooms on its back absorb most of the nutrition." },
                { "47", "I", "Parasect", "Parasect", "bug", "grass", "Mushroom Pokémon", "50", "50", "1", "29.5", "75",
                        "5120", "60", "95", "80", "60", "80", "30", "Effect Spore", "Dry Skin", "", "Damp", "1", "4", "0.5",
                        "0.5", "0.25", "2", "0.5", "2", "0.25", "4", "1", "2", "2", "1", "1", "1", "1", "1", "0", "0", "0",
                        "Paras", "Level ", "Parasect", "", "", "", "", "", "", "",
                        "The bug host is drained of energy by the mushroom on its back. The mushroom appears to do all the thinking." },
                { "48", "I", "Venonat", "Kongpang", "bug", "poison", "Insect Pokémon", "50", "50", "1", "30", "190", "5120",
                        "60", "55", "50", "40", "55", "45", "Compound Eyes", "Tinted Lens", "", "Run Away", "1", "2", "1",
                        "1", "0.25", "1", "0.25", "0.5", "1", "2", "2", "0.5", "2", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Venonat", "Level ", "Venomoth", "", "", "", "", "", "", "",
                        "Its large eyes act as radar. In a bright place, you can see that they are clusters of many tiny eyes." },
                { "49", "I", "Venomoth", "Morphon", "bug", "poison", "Poison Moth Pokémon", "50", "50", "1.5", "12.5", "75",
                        "5120", "70", "65", "60", "90", "75", "90", "Shield Dust", "Tinted Lens", "", "Wonder Skin", "1",
                        "2", "1", "1", "0.25", "1", "0.25", "0.5", "1", "2", "2", "0.5", "2", "1", "1", "1", "1", "0.5",
                        "0", "0", "0", "Venonat", "Level ", "Venomoth", "", "", "", "", "", "", "",
                        "The powdery scales on its wings are hard to remove from skin. They also contain poison that leaks out on contact." },
                { "50", "I", "Diglett", "Digda", "ground", "ground", "Mole Pokémon", "50.2", "49.8", "0.2", "0.8", "255",
                        "5120", "10", "55", "25", "35", "45", "95", "Sand Veil", "Arena Trap", "", "Sand Force", "1", "1",
                        "2", "0", "2", "2", "1", "0.5", "1", "1", "1", "1", "0.5", "1", "1", "1", "1", "1", "0", "0", "0",
                        "Diglett", "Level", "Dugtrio", "", "", "", "", "", "", "",
                        "If a Diglett digs through a field, it leaves the soil perfectly tilled and ideal for planting crops." },
                { "51", "I", "Dugtrio", "Dugtrio", "ground", "ground", "Mole Pokémon", "50.2", "49.8", "0.7", "33.3", "50",
                        "5120", "35", "100", "50", "50", "70", "120", "Sand Veil", "Arena Trap", "", "Sand Force", "1", "1",
                        "2", "0", "2", "2", "1", "0.5", "1", "1", "1", "1", "0.5", "1", "1", "1", "1", "1", "0", "0", "0",
                        "Diglett", "Level", "Dugtrio", "", "", "", "", "", "", "",
                        "A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground." },
                { "52", "I", "Meowth", "Nyarth", "normal", "dark", "Scratch Cat Pokémon", "50.2", "49.8", "0.4", "4.2",
                        "255", "5120", "40", "45", "35", "40", "40", "90", "Pickup", "Technician", "", "Unnerve", "1", "1",
                        "1", "1", "1", "1", "2", "1", "1", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "0", "0",
                        "Meowth", "Level", "Persian", "", "", "", "", "Gigantamax Meowth", "", "",
                        "It loves to collect shiny things. If it’s in a good mood, it might even let its Trainer have a look at its hoard of treasures." },
                { "53", "I", "Persian", "Persian", "normal", "dark", "Classy Cat Pokémon", "50.2", "49.8", "1", "32", "90",
                        "5120", "65", "70", "60", "65", "65", "115", "Limber", "Technician", "", "Unnerve", "1", "1", "1",
                        "1", "1", "1", "2", "1", "1", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "0", "0", "Meowth",
                        "Level", "Persian", "", "", "", "", "", "", "",
                        "Getting this prideful Pokémon to warm up to you takes a lot of effort, and it will claw at you the moment it gets annoyed." },
                { "54", "I", "Psyduck", "Koduck", "water", "", "Duck Pokémon", "50.2", "49.8", "0.8", "19.6", "190", "5120",
                        "50", "52", "48", "65", "50", "55", "Damp", "Cloud Nine", "", "Swift Swim", "1", "0.5", "0.5", "2",
                        "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0", "Psyduck",
                        "Level ", "Golduck", "", "", "", "", "", "", "",
                        "Psyduck is constantly beset by headaches. If the Pokémon lets its strange power erupt, apparently the pain subsides for a while." },
                { "55", "I", "Golduck", "Golduck", "water", "", "Duck Pokémon", "50.2", "49.8", "1.7", "76.6", "75", "5120",
                        "80", "82", "78", "95", "80", "85", "Damp", "Cloud Nine", "", "Swift Swim", "1", "0.5", "0.5", "2",
                        "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0", "Psyduck",
                        "Level ", "Golduck", "", "", "", "", "", "", "",
                        "This Pokémon lives in gently flowing rivers. It paddles through the water with its long limbs, putting its graceful swimming skills on display." },
                { "56", "I", "Mankey", "Mankey", "fighting", "", "Pig Monkey Pokémon", "50", "50", "0.5", "28", "190",
                        "5120", "40", "80", "35", "35", "45", "70", "Vital Spirit", "Anger Point", "", "Defiant", "1", "1",
                        "1", "1", "1", "1", "1", "1", "1", "2", "2", "0.5", "0.5", "1", "1", "0.5", "1", "2", "0", "0", "0",
                        "Mankey", "Level ", "Primeape", "", "", "", "", "", "", "",
                        "An agile Pokémon that lives in trees. It angers easily and will not hesitate to attack anything." },
                { "57", "I", "Primeape", "Okorizaru", "fighting", "", "Pig Monkey Pokémon", "50", "50", "1", "32", "75",
                        "5120", "65", "105", "60", "60", "70", "95", "Vital Spirit", "Anger Point", "", "Defiant", "1", "1",
                        "1", "1", "1", "1", "1", "1", "1", "2", "2", "0.5", "0.5", "1", "1", "0.5", "1", "2", "0", "0", "0",
                        "Mankey", "Level ", "Primeape", "", "", "", "", "", "", "",
                        "It stops being angry only when nobody else is around. To view this moment is very difficult." },
                { "58", "I", "Growlithe", "Gardie", "fire", "", "Puppy Pokémon", "75.49", "24.51", "0.7", "19", "190",
                        "5120", "55", "70", "45", "70", "50", "60", "Intimidate", "Flash Fire", "", "Justified", "1", "0.5",
                        "2", "1", "0.5", "0.5", "1", "1", "2", "1", "1", "0.5", "2", "1", "1", "1", "0.5", "0.5", "0", "0",
                        "0", "Growlithe", "Use Fire Stone", "Arcanine", "", "", "", "", "", "", "",
                        "It has a brave and trustworthy nature. It fearlessly stands up to bigger and stronger foes." },
                { "59", "I", "Arcanine", "Windie", "fire", "", "Legendary Pokémon", "75.49", "24.51", "1.9", "155", "75",
                        "5120", "90", "110", "80", "100", "80", "95", "Intimidate", "Flash Fire", "", "Justified", "1",
                        "0.5", "2", "1", "0.5", "0.5", "1", "1", "2", "1", "1", "0.5", "2", "1", "1", "1", "0.5", "0.5",
                        "0", "0", "0", "Growlithe", "Use Fire Stone", "Arcanine", "", "", "", "", "", "", "",
                        "The sight of it running over 6,200 miles in a single day and night has captivated many people." },
                { "60", "I", "Poliwag", "Nyoromo", "water", "", "Tadpole Pokémon", "50.2", "49.8", "0.6", "12.4", "255",
                        "5120", "40", "50", "40", "40", "40", "90", "Water Absorb", "Damp", "", "Swift Swim", "1", "0.5",
                        "0.5", "2", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0",
                        "Poliwag", "Level", "Poliwhirl", "Use Water Stone", "Poliwrath", "Trade with  King's Rock",
                        "Politoed", "", "", "",
                        "For Poliwag, swimming is easier than walking. The swirl pattern on its belly is actually part of the Pokémon’s innards showing through the skin." },
                { "61", "I", "Poliwhirl", "Nyorozo", "water", "", "Tadpole Pokémon", "50.2", "49.8", "1", "20", "120",
                        "5120", "65", "65", "65", "50", "50", "90", "Water Absorb", "Damp", "", "Swift Swim", "1", "0.5",
                        "0.5", "2", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0",
                        "Poliwag", "Level", "Poliwhirl", "Use Water Stone", "Poliwrath", "Trade with  King's Rock",
                        "Politoed", "", "", "",
                        "Staring at the swirl on its belly causes drowsiness. This trait of Poliwhirl’s has been used in place of lullabies to get children to go to sleep." },
                { "62", "I", "Poliwrath", "Nyorobon", "water", "fighting", "Tadpole Pokémon", "50.2", "49.8", "1.3", "54",
                        "45", "5120", "90", "95", "95", "70", "90", "70", "Water Absorb", "Damp", "", "Swift Swim", "1",
                        "0.5", "0.5", "2", "2", "0.5", "1", "1", "1", "2", "2", "0.5", "0.5", "1", "1", "0.5", "0.5", "2",
                        "0", "0", "0", "Poliwag", "Level", "Poliwhirl", "Use Water Stone", "Poliwrath", "", "", "", "", "",
                        "Its body is solid muscle. When swimming through cold seas, Poliwrath uses its impressive arms to smash through drift ice and plow forward." },
                { "63", "I", "Abra", "Casey", "psychic", "", "Psi Pokémon", "75.49", "24.51", "0.9", "19.5", "200", "5120",
                        "25", "20", "15", "105", "55", "90", "Synchronize", "Inner Focus", "", "Magic Guard", "1", "1", "1",
                        "1", "1", "1", "0.5", "1", "1", "1", "0.5", "2", "1", "2", "1", "2", "1", "1", "0", "0", "0",
                        "Abra", "Level ", "Kadabra", "Trade", "Alakazam", "", "", "", "", "",
                        "This Pokémon uses its psychic powers while it sleeps. The contents of Abra’s dreams affect the powers that the Pokémon wields." },
                { "64", "I", "Kadabra", "Yungerer", "psychic", "", "Psi Pokémon", "75.49", "24.51", "1.3", "56.5", "100",
                        "5120", "40", "35", "30", "120", "70", "105", "Synchronize", "Inner Focus", "", "Magic Guard", "1",
                        "1", "1", "1", "1", "1", "0.5", "1", "1", "1", "0.5", "2", "1", "2", "1", "2", "1", "1", "0", "0",
                        "0", "Abra", "Level ", "Kadabra", "Trade", "Alakazam", "", "", "", "", "",
                        "Using its psychic power, Kadabra levitates as it sleeps. It uses its springy tail as a pillow." },
                { "65", "I", "Alakazam", "Foodin", "psychic", "", "Psi Pokémon", "75.49", "24.51", "1.5", "48", "50",
                        "5120", "55", "50", "45", "135", "95", "120", "Synchronize", "Inner Focus", "", "Magic Guard", "1",
                        "1", "1", "1", "1", "1", "0.5", "1", "1", "1", "0.5", "2", "1", "2", "1", "2", "1", "1", "0", "0",
                        "0", "Abra", "Level ", "Kadabra", "Trade", "Alakazam", "", "", "", "Mega Alakazam", "",
                        "It has an incredibly high level of intelligence. Some say that Alakazam remembers everything that ever happens to it, from birth till death." },
                { "66", "I", "Machop", "Wanriky", "fighting", "", "Superpower Pokémon", "75.49", "24.51", "0.8", "19.5",
                        "180", "5120", "70", "80", "50", "35", "35", "35", "Guts", "No Guard", "", "Steadfast", "1", "1",
                        "1", "1", "1", "1", "1", "1", "1", "2", "2", "0.5", "0.5", "1", "1", "0.5", "1", "2", "0", "0", "0",
                        "Machop", "Level ", "Machoke", "Trade", "Machamp", "", "", "", "", "",
                        "Its whole body is composed of muscles. Even though it’s the size of a human child, it can hurl 100 grown-ups." },
                { "67", "I", "Machoke", "Goriky", "fighting", "", "Superpower Pokémon", "75.49", "24.51", "1.5", "70.5",
                        "90", "5120", "80", "100", "70", "50", "60", "45", "Guts", "No Guard", "", "Steadfast", "1", "1",
                        "1", "1", "1", "1", "1", "1", "1", "2", "2", "0.5", "0.5", "1", "1", "0.5", "1", "2", "0", "0", "0",
                        "Machop", "Level ", "Machoke", "Trade", "Machamp", "", "", "", "", "",
                        "Its muscular body is so powerful, it must wear a power-save belt to be able to regulate its motions." },
                { "68", "I", "Machamp", "Kairiky", "fighting", "", "Superpower Pokémon", "75.49", "24.51", "1.6", "130",
                        "45", "5120", "90", "130", "80", "65", "85", "55", "Guts", "No Guard", "", "Steadfast", "1", "1",
                        "1", "1", "1", "1", "1", "1", "1", "2", "2", "0.5", "0.5", "1", "1", "0.5", "1", "2", "0", "0", "0",
                        "Machop", "Level ", "Machoke", "Trade", "Machamp", "", "", "Gigantamax Machamp", "", "",
                        "It quickly swings its four arms to rock its opponents with ceaseless punches and chops from all angles." },
                { "69", "I", "Bellsprout", "Madatsubomi", "grass", "poison", "Flower Pokémon", "50", "50", "0.7", "4",
                        "255", "5120", "50", "75", "35", "70", "30", "40", "Chlorophyll", "", "", "Gluttony", "1", "2",
                        "0.5", "0.5", "0.25", "2", "0.5", "1", "1", "2", "2", "1", "1", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Bellsprout", "Level ", "Weepinbell", "Use Leaf Stone", "Victreebel", "", "", "", "", "",
                        "Prefers hot and humid places. It ensnares tiny bugs with its vines and devours them." },
                { "70", "I", "Weepinbell", "Utsudon", "grass", "poison", "Flycatcher Pokémon", "50", "50", "1", "6.4",
                        "120", "5120", "65", "90", "50", "85", "45", "55", "Chlorophyll", "", "", "Gluttony", "1", "2",
                        "0.5", "0.5", "0.25", "2", "0.5", "1", "1", "2", "2", "1", "1", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Bellsprout", "Level ", "Weepinbell", "Use Leaf Stone", "Victreebel", "", "", "", "", "",
                        "When hungry, it swallows anything that moves. Its hapless prey is dissolved by strong acids." },
                { "71", "I", "Victreebel", "Utsubot", "grass", "poison", "Flycatcher Pokémon", "50", "50", "1.7", "15.5",
                        "45", "5120", "80", "105", "65", "100", "70", "70", "Chlorophyll", "", "", "Gluttony", "1", "2",
                        "0.5", "0.5", "0.25", "2", "0.5", "1", "1", "2", "2", "1", "1", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Bellsprout", "Level ", "Weepinbell", "Use Leaf Stone", "Victreebel", "", "", "", "", "",
                        "Lures prey with the sweet aroma of honey. Swallowed whole, the prey is dissolved in a day, bones and all." },
                { "72", "I", "Tentacool", "Menokurage", "water", "poison", "Jellyfish Pokémon", "50.2", "49.8", "0.9",
                        "45.5", "190", "5120", "40", "40", "35", "50", "100", "70", "Clear Body", "Liquid Ooze", "",
                        "Rain Dish", "1", "0.5", "0.5", "2", "1", "0.5", "0.5", "0.5", "2", "1", "2", "0.5", "1", "1", "1",
                        "1", "0.5", "0.5", "0", "0", "0", "Tentacool", "Level ", "Tentacruel", "", "", "", "", "", "", "",
                        "Tentacool is not a particularly strong swimmer. It drifts across the surface of shallow seas as it searches for prey." },
                { "73", "I", "Tentacruel", "Dokukurage", "water", "poison", "Jellyfish Pokémon", "50.2", "49.8", "1.6",
                        "55", "60", "5120", "80", "70", "65", "80", "120", "100", "Clear Body", "Liquid Ooze", "",
                        "Rain Dish", "1", "0.5", "0.5", "2", "1", "0.5", "0.5", "0.5", "2", "1", "2", "0.5", "1", "1", "1",
                        "1", "0.5", "0.5", "0", "0", "0", "Tentacool", "Level ", "Tentacruel", "", "", "", "", "", "", "",
                        "When the red orbs on Tentacruel’s head glow brightly, watch out. The Pokémon is about to fire off a burst of ultrasonic waves." },
                { "74", "I", "Geodude", "Isitsubute", "rock", "ground", "Rock Pokémon", "50", "50", "0.4", "20", "255",
                        "3840", "40", "80", "100", "30", "30", "20", "Rock Head", "Sturdy", "", "Sand Veil", "0.5", "0.5",
                        "4", "0", "4", "2", "2", "0.25", "2", "0.5", "1", "1", "0.5", "1", "1", "1", "2", "1", "0", "0",
                        "0", "Geodude", "Level", "Graveler", "Trade", "Golem", "", "", "", "", "",
                        "Commonly found near mountain trails and the like. If you step on one by accident, it gets angry." },
                { "75", "I", "Graveler", "Golone", "rock", "ground", "Rock Pokémon", "50", "50", "1", "105", "120", "3840",
                        "55", "95", "115", "45", "45", "35", "Rock Head", "Sturdy", "", "Sand Veil", "0.5", "0.5", "4", "0",
                        "4", "2", "2", "0.25", "2", "0.5", "1", "1", "0.5", "1", "1", "1", "2", "1", "0", "0", "0",
                        "Geodude", "Level", "Graveler", "Trade", "Golem", "", "", "", "", "",
                        "Often seen rolling down mountain trails. Obstacles are just things to roll straight over, not avoid." },
                { "76", "I", "Golem", "Golonya", "rock", "ground", "Megaton Pokémon", "50", "50", "1.4", "300", "45",
                        "3840", "80", "120", "130", "55", "65", "45", "Rock Head", "Sturdy", "", "Sand Veil", "0.5", "0.5",
                        "4", "0", "4", "2", "2", "0.25", "2", "0.5", "1", "1", "0.5", "1", "1", "1", "2", "1", "0", "0",
                        "0", "Geodude", "Level", "Graveler", "Trade", "Golem", "", "", "", "", "",
                        "Once it sheds its skin, its body turns tender and whitish. Its hide hardens when it’s exposed to air." },
                { "77", "I", "Ponyta", "Ponyta", "fire", "psychic", "Fire Horse Pokémon", "50.2", "49.8", "1", "30", "190",
                        "5120", "50", "85", "55", "65", "65", "90", "Run Away", "Flash Fire", "", "Flame Body", "1", "0.5",
                        "2", "1", "0.5", "0.5", "1", "1", "2", "1", "1", "0.5", "2", "1", "1", "1", "0.5", "0.5", "0", "0",
                        "0", "Ponyta", "Level", "Rapidash", "", "", "", "", "", "", "",
                        "It can’t run properly when it’s newly born. As it races around with others of its kind, its legs grow stronger." },
                { "78", "I", "Rapidash", "Gallop", "fire", "psychic", "Fire Horse Pokémon", "50.2", "49.8", "1.7", "95",
                        "60", "5120", "65", "100", "70", "80", "80", "105", "Run Away", "Flash Fire", "", "Flame Body", "1",
                        "0.5", "2", "1", "0.5", "0.5", "1", "1", "2", "1", "1", "0.5", "2", "1", "1", "1", "0.5", "0.5",
                        "0", "0", "0", "Ponyta", "Level", "Rapidash", "", "", "", "", "", "", "",
                        "This Pokémon can be seen galloping through fields at speeds of up to 150 mph, its fiery mane fluttering in the wind." },
                { "79", "I", "Slowpoke", "Yadon", "water", "psychic", "Dopey Pokémon", "50.2", "49.8", "1.2", "36", "190",
                        "5120", "90", "65", "65", "40", "40", "15", "Oblivious", "Own Tempo", "", "Regenerator", "1", "0.5",
                        "0.5", "2", "2", "0.5", "0.5", "1", "1", "1", "0.5", "2", "1", "2", "1", "2", "0.5", "1", "0", "0",
                        "0", "Slowpoke", "Level", "Slowbro", "Trade with  King's Rock", "Slowking", "Slowpoke",
                        "Use Galarica Cuff", "", "", "",
                        "Slow-witted and oblivious, this Pokémon won’t feel any pain if its tail gets eaten. It won’t notice when its tail grows back, either." },
                { "80", "I", "Slowbro", "Yadoran", "water", "psychic", "Hermit Crab Pokémon", "50.2", "49.8", "1.6", "78.5",
                        "75", "5120", "95", "75", "110", "100", "80", "30", "Oblivious", "Own Tempo", "", "Regenerator",
                        "1", "0.5", "0.5", "2", "2", "0.5", "0.5", "1", "1", "1", "0.5", "2", "1", "2", "1", "2", "0.5",
                        "1", "0", "0", "0", "Slowpoke", "Level", "Slowbro", "Trade with  King's Rock", "Slowking",
                        "Slowpoke", "Use Galarica Cuff", "", "Mega Slowbro", "",
                        "Slowpoke became Slowbro when a Shellder bit on to its tail. Sweet flavors seeping from the tail make the Shellder feel as if its life is a dream." },
                { "81", "I", "Magnemite", "Coil", "electric", "steel", "Magnet Pokémon", "", "", "0.3", "6", "190", "5120",
                        "25", "35", "70", "95", "55", "45", "Magnet Pull", "Sturdy", "", "Analytic", "0.5", "2", "1", "0.5",
                        "0.5", "0.5", "2", "0", "4", "0.25", "0.5", "0.5", "0.5", "1", "0.5", "1", "0.25", "0.5", "0", "0",
                        "0", "Magnemite", "Level ", "Magneton", "Use Thunder Stone", "Magnezone", "", "", "", "", "",
                        "At times, Magnemite runs out of electricity and ends up on the ground. If you give batteries to a grounded Magnemite, it’ll start moving again." },
                { "82", "I", "Magneton", "Rarecoil", "electric", "steel", "Magnet Pokémon", "", "", "1", "60", "60", "5120",
                        "50", "60", "95", "120", "70", "70", "Magnet Pull", "Sturdy", "", "Analytic", "0.5", "2", "1",
                        "0.5", "0.5", "0.5", "2", "0", "4", "0.25", "0.5", "0.5", "0.5", "1", "0.5", "1", "0.25", "0.5",
                        "0", "0", "0", "Magnemite", "Level ", "Magneton", "Use Thunder Stone", "Magnezone", "", "", "", "",
                        "",
                        "This Pokémon is three Magnemite that have linked together. Magneton sends out powerful radio waves to study its surroundings." },
                { "83", "I", "Farfetchd", "Kamonegi", "normal", "flying", "Wild Duck Pokémon", "50.2", "49.8", "0.8", "15",
                        "45", "5120", "52", "90", "55", "58", "62", "60", "Keen Eye", "Inner Focus", "", "Defiant", "1",
                        "1", "1", "2", "0.5", "2", "1", "1", "0", "1", "1", "0.5", "2", "0", "1", "1", "1", "1", "0", "0",
                        "0", "Farfetchd", "Get 3 Critical Hits in one battle", "Sirfetch'd", "", "", "", "", "", "", "",
                        "The stalk this Pokémon carries in its wings serves as a sword to cut down opponents. In a dire situation, the stalk can also serve as food." },
                { "84", "I", "Doduo", "Dodo", "normal", "flying", "Twin Bird Pokémon", "50", "50", "1.4", "39.2", "190",
                        "5120", "35", "85", "45", "35", "35", "75", "Run Away", "Early Bird", "", "Tangled Feet", "1", "1",
                        "1", "2", "0.5", "2", "1", "1", "0", "1", "1", "0.5", "2", "0", "1", "1", "1", "1", "0", "0", "0",
                        "Doduo", "Level ", "Dodrio", "", "", "", "", "", "", "",
                        "Its short wings make flying difficult. Instead, this Pokémon runs at high speed on developed legs." },
                { "85", "I", "Dodrio", "Dodorio", "normal", "flying", "Triple Bird Pokémon", "50", "50", "1.8", "85.2",
                        "45", "5120", "60", "110", "70", "60", "60", "110", "Run Away", "Early Bird", "", "Tangled Feet",
                        "1", "1", "1", "2", "0.5", "2", "1", "1", "0", "1", "1", "0.5", "2", "0", "1", "1", "1", "1", "0",
                        "0", "0", "Doduo", "Level ", "Dodrio", "", "", "", "", "", "", "",
                        "One of Doduo’s two heads splits to form a unique species. It runs close to 40 mph in prairies." },
                { "86", "I", "Seel", "Pawou", "water", "", "Sea Lion Pokémon", "50", "50", "1.1", "90", "190", "5120", "65",
                        "45", "55", "45", "70", "45", "Thick Fat", "Hydration", "", "Ice Body", "1", "0.5", "0.5", "2", "2",
                        "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0", "Seel",
                        "Level ", "Dewgong", "", "", "", "", "", "", "",
                        "Loves freezing-cold conditions. Relishes swimming in a frigid climate of around 14 degrees Fahrenheit." },
                { "87", "I", "Dewgong", "Jugon", "water", "ice", "Sea Lion Pokémon", "50", "50", "1.7", "120", "75", "5120",
                        "90", "70", "80", "70", "95", "70", "Thick Fat", "Hydration", "", "Ice Body", "1", "1", "0.5", "2",
                        "2", "0.25", "2", "1", "1", "1", "1", "1", "2", "1", "1", "1", "1", "1", "0", "0", "0", "Seel",
                        "Level ", "Dewgong", "", "", "", "", "", "", "",
                        "Its entire body is a snowy white. Unharmed by even intense cold, it swims powerfully in icy waters." },
                { "88", "I", "Grimer", "Betbeter", "poison", "poison", "Sludge Pokémon", "50", "50", "0.9", "30", "190",
                        "5120", "80", "80", "50", "40", "50", "25", "Stench", "Sticky Hold", "", "Poison Touch", "1", "1",
                        "1", "1", "0.5", "1", "0.5", "0.5", "2", "1", "2", "0.5", "1", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Grimer", "Level", "Muk", "", "", "", "", "", "", "",
                        "Made of congealed sludge. It smells too putrid to touch. Even weeds won’t grow in its path." },
                { "89", "I", "Muk", "Betbeton", "poison", "poison", "Sludge Pokémon", "50", "50", "1.2", "30", "75", "5120",
                        "105", "105", "75", "65", "100", "50", "Stench", "Sticky Hold", "", "Poison Touch", "1", "1", "1",
                        "1", "0.5", "1", "0.5", "0.5", "2", "1", "2", "0.5", "1", "1", "1", "1", "1", "0.5", "0", "0", "0",
                        "Grimer", "Level", "Muk", "", "", "", "", "", "", "",
                        "Smells so awful, it can cause fainting. Through degeneration of its nose, it lost its sense of smell." },
                { "90", "I", "Shellder", "Shellder", "water", "", "Bivalve Pokémon", "50.2", "49.8", "0.3", "4", "190",
                        "5120", "30", "65", "100", "45", "25", "40", "Shell Armor", "Skill Link", "", "Overcoat", "1",
                        "0.5", "0.5", "2", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0",
                        "0", "0", "Shellder", "Use Water Stone", "Cloyster", "", "", "", "", "", "", "",
                        "It swims facing backward by opening and closing its two-piece shell. It is surprisingly fast." },
                { "91", "I", "Cloyster", "Parshen", "water", "ice", "Bivalve Pokémon", "50.2", "49.8", "1.5", "132.5", "60",
                        "5120", "50", "95", "180", "85", "45", "70", "Shell Armor", "Skill Link", "", "Overcoat", "1", "1",
                        "0.5", "2", "2", "0.25", "2", "1", "1", "1", "1", "1", "2", "1", "1", "1", "1", "1", "0", "0", "0",
                        "Shellder", "Use Water Stone", "Cloyster", "", "", "", "", "", "", "",
                        "Its shell is extremely hard. It cannot be shattered, even with a bomb. The shell opens only when it is attacking." },
                { "92", "I", "Gastly", "Ghos", "ghost", "poison", "Gas Pokémon", "50.2", "49.8", "1.3", "0.1", "190",
                        "5120", "30", "35", "30", "100", "35", "80", "Levitate", "", "", "", "0", "1", "1", "1", "0.5", "1",
                        "0", "0.25", "2", "1", "2", "0.25", "1", "2", "1", "2", "1", "0.5", "0", "0", "0", "Gastly",
                        "Level ", "Haunter", "Trade", "Gengar", "", "", "", "", "",
                        "Born from gases, anyone would faint if engulfed by its gaseous body, which contains poison." },
                { "93", "I", "Haunter", "Ghost", "ghost", "poison", "Gas Pokémon", "50.2", "49.8", "1.6", "0.1", "90",
                        "5120", "45", "50", "45", "115", "55", "95", "Levitate", "", "", "", "0", "1", "1", "1", "0.5", "1",
                        "0", "0.25", "2", "1", "2", "0.25", "1", "2", "1", "2", "1", "0.5", "0", "0", "0", "Gastly",
                        "Level ", "Haunter", "Trade", "Gengar", "", "", "", "", "",
                        "Its tongue is made of gas. If licked, its victim starts shaking constantly until death eventually comes." },
                { "94", "I", "Gengar", "Gangar", "ghost", "poison", "Shadow Pokémon", "50.2", "49.8", "1.5", "40.5", "45",
                        "5120", "60", "65", "60", "130", "75", "110", "Cursed Body", "", "", "", "0", "1", "1", "1", "0.5",
                        "1", "0", "0.25", "2", "1", "2", "0.25", "1", "2", "1", "2", "1", "0.5", "0", "0", "0", "Gastly",
                        "Level ", "Haunter", "Trade", "Gengar", "", "", "Gigantamax Gengar", "Mega Gengar", "",
                        "On the night of a full moon, if shadows move on their own and laugh, it must be Gengar’s doing." },
                { "95", "I", "Onix", "Iwark", "rock", "ground", "Rock Snake Pokémon", "50.2", "49.8", "8.8", "210", "45",
                        "6400", "35", "45", "160", "30", "45", "70", "Rock Head", "Sturdy", "", "Weak Armor", "0.5", "0.5",
                        "4", "0", "4", "2", "2", "0.25", "2", "0.5", "1", "1", "0.5", "1", "1", "1", "2", "1", "0", "0",
                        "0", "Onix", "Trade with  Metal Coat", "Steelix", "", "", "", "", "", "", "",
                        "As it digs through the ground, it absorbs many hard objects. This is what makes its body so solid." },
                { "96", "I", "Drowzee", "Sleepe", "psychic", "", "Hypnosis Pokémon", "50", "50", "1", "32.4", "190", "5120",
                        "60", "48", "45", "43", "90", "42", "Insomnia", "Forewarn", "", "Inner Focus", "1", "1", "1", "1",
                        "1", "1", "0.5", "1", "1", "1", "0.5", "2", "1", "2", "1", "2", "1", "1", "0", "0", "0", "Drowzee",
                        "Level ", "Hypno", "", "", "", "", "", "", "",
                        "If you sleep by it all the time, it will sometimes show you dreams it had eaten in the past." },
                { "97", "I", "Hypno", "Sleeper", "psychic", "", "Hypnosis Pokémon", "50", "50", "1.6", "75.6", "75", "5120",
                        "85", "73", "70", "73", "115", "67", "Insomnia", "Forewarn", "", "Inner Focus", "1", "1", "1", "1",
                        "1", "1", "0.5", "1", "1", "1", "0.5", "2", "1", "2", "1", "2", "1", "1", "0", "0", "0", "Drowzee",
                        "Level ", "Hypno", "", "", "", "", "", "", "",
                        "Avoid eye contact if you come across one. It will try to put you to sleep by using its pendulum." },
                { "98", "I", "Krabby", "Crab", "water", "", "River Crab Pokémon", "50.2", "49.8", "0.4", "6.5", "225",
                        "5120", "30", "105", "90", "25", "25", "50", "Hyper Cutter", "Shell Armor", "", "Sheer Force", "1",
                        "0.5", "0.5", "2", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0",
                        "0", "0", "Krabby", "Level ", "Kingler", "", "", "", "", "", "", "",
                        "It can be found near the sea. The large pincers grow back if they are torn out of their sockets." },
                { "99", "I", "Kingler", "Kingler", "water", "", "Pincer Pokémon", "50.2", "49.8", "1.3", "60", "60", "5120",
                        "55", "130", "115", "50", "50", "75", "Hyper Cutter", "Shell Armor", "", "Sheer Force", "1", "0.5",
                        "0.5", "2", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0",
                        "Krabby", "Level ", "Kingler", "", "", "", "", "Gigantamax Kingler", "", "",
                        "Its large and hard pincer has 10,000-horsepower strength. However, being so big, it is unwieldy to move." },
                { "100", "I", "Voltorb", "Biriridama", "electric", "", "Ball Pokémon", "", "", "0.5", "10.4", "190", "5120",
                        "40", "30", "50", "55", "55", "100", "Soundproof", "Static", "", "Aftermath", "1", "1", "1", "0.5",
                        "1", "1", "1", "1", "2", "0.5", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0", "Voltorb",
                        "Level ", "Electrode", "", "", "", "", "", "", "",
                        "It is said to camouflage itself as a Poké Ball. It will self-destruct with very little stimulus." },
                { "101", "I", "Electrode", "Marumine", "electric", "", "Ball Pokémon", "", "", "1.2", "66.6", "60", "5120",
                        "60", "50", "70", "80", "80", "150", "Soundproof", "Static", "", "Aftermath", "1", "1", "1", "0.5",
                        "1", "1", "1", "1", "2", "0.5", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0", "Voltorb",
                        "Level ", "Electrode", "", "", "", "", "", "", "",
                        "Stores electrical energy inside its body. Even the slightest shock could trigger a huge explosion." },
                { "102", "I", "Exeggcute", "Tamatama", "grass", "psychic", "Egg Pokémon", "50.2", "49.8", "0.4", "2.5",
                        "90", "5120", "60", "40", "80", "60", "45", "40", "Chlorophyll", "", "", "Harvest", "1", "2", "0.5",
                        "0.5", "0.5", "2", "0.5", "2", "0.5", "2", "0.5", "4", "1", "2", "1", "2", "1", "1", "0", "0", "0",
                        "Exeggcute", "Use Leaf Stone", "Exeggutor", "", "", "", "", "", "", "",
                        "Though it may look like it’s just a bunch of eggs, it’s a proper Pokémon. Exeggcute communicates with others of its kind via telepathy, apparently." },
                { "103", "I", "Exeggutor", "Nassy", "grass", "psychic", "Coconut Pokémon", "50.2", "49.8", "2", "120", "45",
                        "5120", "95", "95", "85", "125", "75", "55", "Chlorophyll", "", "", "Frisk- Harvest", "1", "2",
                        "0.5", "0.5", "0.5", "2", "0.5", "2", "0.5", "2", "0.5", "4", "1", "2", "1", "2", "1", "1", "0",
                        "0", "0", "Exeggcute", "Use Leaf Stone", "Exeggutor", "", "", "", "", "", "", "",
                        "Each of Exeggutor’s three heads is thinking different thoughts. The three don’t seem to be very interested in one another." },
                { "104", "I", "Cubone", "Karakara", "ground", "", "Lonely Pokémon", "50.2", "49.8", "0.4", "6.5", "190",
                        "5120", "50", "50", "95", "40", "50", "35", "Rock Head", "Lightning Rod", "", "Battle Armor", "1",
                        "1", "2", "0", "2", "2", "1", "0.5", "1", "1", "1", "1", "0.5", "1", "1", "1", "1", "1", "0", "0",
                        "0", "Cubone", "Level", "Marowak", "", "", "", "", "", "", "",
                        "When the memory of its departed mother brings it to tears, its cries echo mournfully within the skull it wears on its head." },
                { "105", "I", "Marowak", "Garagara", "ground", "fire", "Bone Keeper Pokémon", "50.2", "49.8", "1", "45",
                        "75", "5120", "60", "80", "110", "50", "80", "45", "Rock Head", "Lightning Rod", "", "Battle Armor",
                        "1", "1", "2", "0", "2", "2", "1", "0.5", "1", "1", "1", "1", "0.5", "1", "1", "1", "1", "1", "0",
                        "0", "0", "Cubone", "Level", "Marowak", "", "", "", "", "", "", "",
                        "This Pokémon overcame its sorrow to evolve a sturdy new body. Marowak faces its opponents bravely, using a bone as a weapon." },
                { "106", "I", "Hitmonlee", "Sawamular", "fighting", "", "Kicking Pokémon", "100", "0", "1.5", "49.8", "45",
                        "6400", "50", "120", "53", "35", "110", "87", "Limber", "Reckless", "", "Unburden", "1", "1", "1",
                        "1", "1", "1", "1", "1", "1", "2", "2", "0.5", "0.5", "1", "1", "0.5", "1", "2", "0", "0", "0",
                        "Tyrogue", "Attack > Defence at Level 20", "Hitmonlee", "", "", "", "", "", "", "",
                        "This amazing Pokémon has an awesome sense of balance. It can kick in succession from any position." },
                { "107", "I", "Hitmonchan", "Ebiwalar", "fighting", "", "Punching Pokémon", "100", "0", "1.4", "50.2", "45",
                        "6400", "50", "105", "79", "35", "110", "76", "Keen Eye", "Iron Fist", "", "Inner Focus", "1", "1",
                        "1", "1", "1", "1", "1", "1", "1", "2", "2", "0.5", "0.5", "1", "1", "0.5", "1", "2", "0", "0", "0",
                        "Tyrogue", "Attack < Defence at Level 20", "Hitmonchan", "", "", "", "", "", "", "",
                        "Its punches slice the air. They are launched at such high speed, even a slight graze could cause a burn." },
                { "108", "I", "Lickitung", "Beroringa", "normal", "", "Licking Pokémon", "50.2", "49.8", "1.2", "65.5",
                        "45", "5120", "90", "55", "75", "60", "75", "30", "Own Tempo", "Oblivious", "", "Cloud Nine", "1",
                        "1", "1", "1", "1", "1", "2", "1", "1", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "0", "0",
                        "Lickitung", "Level up while knowing  Rollout", "Lickilicky", "", "", "", "", "", "", "",
                        "If this Pokémon’s sticky saliva gets on you and you don’t clean it off, an intense itch will set in. The itch won’t go away, either." },
                { "109", "I", "Koffing", "Dogars", "poison", "", "Poison Gas Pokémon", "50.2", "49.8", "0.6", "1", "190",
                        "5120", "40", "65", "95", "60", "45", "35", "Levitate", "Neutralizing Gas", "", "Stench", "1", "1",
                        "1", "1", "0.5", "1", "0.5", "0.5", "2", "1", "2", "0.5", "1", "1", "1", "1", "1", "0.5", "0", "0",
                        "0", "Koffing", "Level", "Weezing", "", "", "", "", "", "", "",
                        "Its body is full of poisonous gas. It floats into garbage dumps, seeking out the fumes of raw, rotting trash." },
                { "110", "I", "Weezing", "Matadogas", "poison", "poison", "Poison Gas Pokémon", "50.2", "49.8", "1.2",
                        "9.5", "60", "5120", "65", "90", "120", "85", "70", "60", "Levitate", "Neutralizing Gas", "",
                        "Stench", "1", "1", "1", "1", "0.5", "1", "0.5", "0.5", "2", "1", "2", "0.5", "1", "1", "1", "1",
                        "1", "0.5", "0", "0", "0", "Koffing", "Level", "Weezing", "", "", "", "", "", "", "",
                        "It mixes gases between its two bodies. It’s said that these Pokémon were seen all over the Galar region back in the day." },
                { "111", "I", "Rhyhorn", "Sihorn", "ground", "rock", "Spikes Pokémon", "50.2", "49.8", "1", "115", "120",
                        "5120", "80", "85", "95", "30", "30", "25", "Lightning Rod", "Rock Head", "", "Reckless", "0.5",
                        "0.5", "4", "0", "4", "2", "2", "0.25", "2", "0.5", "1", "1", "0.5", "1", "1", "1", "2", "1", "0",
                        "0", "0", "Rhyhorn", "Level ", "Rhydon", "Trade with  Protector", "Rhyperior", "", "", "", "", "",
                        "Strong, but not too bright, this Pokémon can shatter even a skyscraper with its charging tackles." },
                { "112", "I", "Rhydon", "Sidon", "ground", "rock", "Drill Pokémon", "50.2", "49.8", "1.9", "120", "60",
                        "5120", "105", "130", "120", "45", "45", "40", "Lightning Rod", "Rock Head", "", "Reckless", "0.5",
                        "0.5", "4", "0", "4", "2", "2", "0.25", "2", "0.5", "1", "1", "0.5", "1", "1", "1", "2", "1", "0",
                        "0", "0", "Rhyhorn", "Level ", "Rhydon", "Trade with  Protector", "Rhyperior", "", "", "", "", "",
                        "It begins walking on its hind legs after evolution. It can punch holes through boulders with its horn." },
                { "113", "I", "Chansey", "Lucky", "normal", "", "Egg Pokémon", "0", "100", "1.1", "34.6", "30", "10240",
                        "250", "5", "5", "35", "105", "50", "Natural Cure", "Serene Grace", "", "Healer", "1", "1", "1",
                        "1", "1", "1", "2", "1", "1", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "0", "0", "Happiny",
                        "Level up during day while holding Oval Stone", "Chansey", "Level Up with Happiness Value at 220",
                        "Blissey", "", "", "", "", "",
                        "The egg Chansey carries is not only delicious but also packed with nutrition. It’s used as a high-class cooking ingredient." },
                { "114", "I", "Tangela", "Monjara", "grass", "", "Vine Pokémon", "50.2", "49.8", "1", "35", "45", "5120",
                        "65", "55", "115", "100", "40", "60", "Chlorophyll", "Leaf Guard", "", "Regenerator", "1", "2",
                        "0.5", "0.5", "0.5", "2", "1", "2", "0.5", "2", "1", "2", "1", "1", "1", "1", "1", "1", "0", "0",
                        "0", "Tangela", "Level up while knowing  Ancient Power", "Tangrowth", "", "", "", "", "", "", "",
                        "Hidden beneath a tangle of vines that grows nonstop even if the vines are torn off, this Pokémon’s true appearance remains a mystery." },
                { "115", "I", "Kangaskhan", "Garura", "normal", "", "Parent Pokémon", "0", "100", "2.2", "80", "45", "5120",
                        "105", "95", "80", "40", "80", "90", "Early Bird", "Scrappy", "", "Inner Focus", "1", "1", "1", "1",
                        "1", "1", "2", "1", "1", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "0", "0", "Kangaskhan",
                        "", "", "", "", "", "", "", "Mega Kangaskhan", "",
                        "Although it’s carrying its baby in a pouch on its belly, Kangaskhan is swift on its feet. It intimidates its opponents with quick jabs." },
                { "116", "I", "Horsea", "Tattu", "water", "", "Dragon Pokémon", "50.2", "49.8", "0.4", "8", "225", "5120",
                        "30", "40", "70", "70", "25", "60", "Swift Swim", "Sniper", "", "Damp", "1", "0.5", "0.5", "2", "2",
                        "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0", "Horsea",
                        "Level ", "Seadra", "Trade with  Dragon Scale", "Kingdra", "", "", "", "", "",
                        "Horsea makes its home in oceans with gentle currents. If this Pokémon is under attack, it spits out pitch-black ink and escapes." },
                { "117", "I", "Seadra", "Seadra", "water", "", "Dragon Pokémon", "50.2", "49.8", "1.2", "25", "75", "5120",
                        "55", "65", "95", "95", "45", "85", "Poison Point", "Sniper", "", "Damp", "1", "0.5", "0.5", "2",
                        "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0", "Horsea",
                        "Level ", "Seadra", "Trade with  Dragon Scale", "Kingdra", "", "", "", "", "",
                        "It’s the males that raise the offspring. While Seadra are raising young, the spines on their backs secrete thicker and stronger poison." },
                { "118", "I", "Goldeen", "Tosakinto", "water", "", "Goldfish Pokémon", "50.2", "49.8", "0.6", "15", "225",
                        "5120", "45", "67", "60", "35", "50", "63", "Swift Swim", "Water Veil", "", "Lightning Rod", "1",
                        "0.5", "0.5", "2", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0",
                        "0", "0", "Goldeen", "Level ", "Seaking", "", "", "", "", "", "", "",
                        "Its dorsal, pectoral, and tail fins wave elegantly in water. That is why it is known as the Water Dancer." },
                { "119", "I", "Seaking", "Azumao", "water", "", "Goldfish Pokémon", "50.2", "49.8", "1.3", "39", "60",
                        "5120", "80", "92", "65", "65", "80", "68", "Swift Swim", "Water Veil", "", "Lightning Rod", "1",
                        "0.5", "0.5", "2", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0",
                        "0", "0", "Goldeen", "Level ", "Seaking", "", "", "", "", "", "", "",
                        "In autumn, its body becomes more fatty in preparing to propose to a mate. It takes on beautiful colors." },
                { "120", "I", "Staryu", "Hitodeman", "water", "", "Starshape Pokémon", "", "", "0.8", "34.5", "225", "5120",
                        "30", "45", "55", "70", "55", "85", "Illuminate", "Natural Cure", "", "Analytic", "1", "0.5", "0.5",
                        "2", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0",
                        "Staryu", "Use Water Stone", "Starmie", "", "", "", "", "", "", "",
                        "If you visit a beach at the end of summer, you’ll be able to see groups of Staryu lighting up in a steady rhythm." },
                { "121", "I", "Starmie", "Starmie", "water", "psychic", "Mysterious Pokémon", "", "", "1.1", "80", "60",
                        "5120", "60", "75", "85", "100", "85", "115", "Illuminate", "Natural Cure", "", "Analytic", "1",
                        "0.5", "0.5", "2", "2", "0.5", "0.5", "1", "1", "1", "0.5", "2", "1", "2", "1", "2", "0.5", "1",
                        "0", "0", "0", "Staryu", "Use Water Stone", "Starmie", "", "", "", "", "", "", "",
                        "This Pokémon has an organ known as its core. The organ glows in seven colors when Starmie is unleashing its potent psychic powers." },
                { "122", "I", "Mr. Mime", "Barrierd", "psychic", "fairy", "Barrier Pokémon", "50.2", "49.8", "1.3", "54.5",
                        "45", "6400", "40", "45", "65", "100", "120", "90", "Soundproof", "Filter", "", "Technician", "1",
                        "1", "1", "1", "1", "1", "0.25", "2", "1", "1", "0.5", "1", "1", "2", "0", "1", "2", "1", "0", "0",
                        "0", "Mimejr.", "Level up while knowing  Mimic", "Mr.mime", "", "", "", "", "", "", "",
                        "The broadness of its hands may be no coincidence—many scientists believe its palms became enlarged specifically for pantomiming." },
                { "123", "I", "Scyther", "Strike", "bug", "flying", "Mantis Pokémon", "50.2", "49.8", "1.5", "56", "45",
                        "6400", "70", "110", "80", "55", "80", "105", "Swarm", "Technician", "", "Steadfast", "1", "2", "1",
                        "2", "0.25", "2", "0.25", "1", "0", "2", "1", "0.5", "4", "1", "1", "1", "1", "1", "0", "0", "0",
                        "Scyther", "Trade with  Metal Coat", "Scizor", "", "", "", "", "", "", "",
                        "As Scyther fights more and more battles, its scythes become sharper and sharper. With a single slice, Scyther can fell a massive tree." },
                { "124", "I", "Jynx", "Rougela", "ice", "psychic", "Humanshape Pokémon", "0", "100", "1.4", "40.6", "45",
                        "6400", "65", "50", "35", "115", "95", "95", "Oblivious", "Forewarn", "", "Dry Skin", "1", "2", "1",
                        "1", "1", "0.5", "1", "1", "1", "1", "0.5", "2", "2", "2", "1", "2", "2", "1", "0", "0", "0",
                        "Smoochum", "Level ", "Jynx", "", "", "", "", "", "", "",
                        "In certain parts of Galar, Jynx was once feared and worshiped as the Queen of Ice." },
                { "125", "I", "Electabuzz", "Eleboo", "electric", "", "Electric Pokémon", "75.49", "24.51", "1.1", "30",
                        "45", "6400", "65", "83", "57", "95", "85", "105", "Static", "", "", "Vital Spirit", "1", "1", "1",
                        "0.5", "1", "1", "1", "1", "2", "0.5", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0",
                        "Elekid", "Level ", "Electabuzz", "Trade with  Electirizer", "Electivire", "", "", "", "", "",
                        "Many power plants keep Ground-type Pokémon around as a defense against Electabuzz that come seeking electricity." },
                { "126", "I", "Magmar", "Boober", "fire", "", "Spitfire Pokémon", "75.49", "24.51", "1.3", "44.5", "45",
                        "6400", "65", "95", "57", "100", "85", "93", "Flame Body", "", "", "Vital Spirit", "1", "0.5", "2",
                        "1", "0.5", "0.5", "1", "1", "2", "1", "1", "0.5", "2", "1", "1", "1", "0.5", "0.5", "0", "0", "0",
                        "Magby", "Level ", "Magmar", "Trade with  Magmarizer", "Magmortar", "", "", "", "", "",
                        "Magmar dispatches its prey with fire. But it regrets this habit once it realizes that it has burned its intended prey to a charred crisp." },
                { "127", "I", "Pinsir", "Kailios", "bug", "", "Stagbeetle Pokémon", "50.2", "49.8", "1.5", "55", "45",
                        "6400", "65", "125", "100", "55", "70", "85", "Hyper Cutter", "Mold Breaker", "", "Moxie", "1", "2",
                        "1", "1", "0.5", "1", "0.5", "1", "0.5", "2", "1", "1", "2", "1", "1", "1", "1", "1", "0", "0", "0",
                        "Pinsir", "", "", "", "", "", "", "", "Mega Pinsir", "",
                        "These Pokémon judge one another based on pincers. Thicker, more impressive pincers make for more popularity with the opposite gender." },
                { "128", "I", "Tauros", "Kentauros", "normal", "", "Wild Bull Pokémon", "100", "0", "1.4", "88.4", "45",
                        "5120", "75", "100", "95", "40", "70", "110", "Intimidate", "Anger Point", "", "Sheer Force", "1",
                        "1", "1", "1", "1", "1", "2", "1", "1", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "0", "0",
                        "Tauros", "", "", "", "", "", "", "", "", "",
                        "When Tauros begins whipping itself with its tails, it’s a warning that the Pokémon is about to charge with astounding speed." },
                { "129", "I", "Magikarp", "Koiking", "water", "", "Fish Pokémon", "50.2", "49.8", "0.9", "10", "255",
                        "1280", "20", "10", "55", "15", "20", "80", "Swift Swim", "", "", "Rattled", "1", "0.5", "0.5", "2",
                        "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0", "Magikarp",
                        "Level ", "Gyarados", "", "", "", "", "", "", "",
                        "It is virtually worthless in terms of both power and speed. It is the most weak and pathetic Pokémon in the world." },
                { "130", "I", "Gyarados", "Gyarados", "water", "flying", "Atrocious Pokémon", "50.2", "49.8", "6.5", "235",
                        "45", "1280", "95", "125", "79", "60", "100", "81", "Intimidate", "", "", "Moxie", "1", "0.5",
                        "0.5", "4", "1", "1", "0.5", "1", "0", "1", "1", "0.5", "2", "1", "1", "1", "0.5", "1", "0", "0",
                        "0", "Magikarp", "Level ", "Gyarados", "", "", "", "", "", "Mega Gyarados", "",
                        "It has an extremely aggressive nature. The Hyper Beam it shoots from its mouth totally incinerates all targets." },
                { "131", "I", "Lapras", "Laplace", "water", "ice", "Transport Pokémon", "50.2", "49.8", "2.5", "220", "45",
                        "10240", "130", "85", "80", "85", "95", "60", "Water Absorb", "Shell Armor", "", "Hydration", "1",
                        "1", "0.5", "2", "2", "0.25", "2", "1", "1", "1", "1", "1", "2", "1", "1", "1", "1", "1", "0", "0",
                        "0", "Lapras", "", "", "", "", "", "", "Gigantamax Lapras", "", "",
                        "A smart and kindhearted Pokémon, it glides across the surface of the sea while its beautiful song echoes around it." },
                { "132", "I", "Ditto", "Metamon", "normal", "", "Transform Pokémon", "", "", "0.3", "4", "35", "5120", "48",
                        "48", "48", "48", "48", "48", "Limber", "", "", "Imposter", "1", "1", "1", "1", "1", "1", "2", "1",
                        "1", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "0", "0", "Ditto", "", "", "", "", "", "",
                        "", "", "",
                        "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes." },
                { "133", "I", "Eevee", "Eievui", "normal", "", "Evolution Pokémon", "88.14", "11.86", "0.3", "6.5", "45",
                        "8960", "55", "55", "50", "45", "65", "55", "Run Away", "Adaptability", "", "Anticipation", "1",
                        "1", "1", "1", "1", "1", "2", "1", "1", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "0", "0",
                        "Eevee", "", "", "", "", "", "", "Gigantamax Eevee", "", "",
                        "It has the ability to alter the composition of its body to suit its surrounding environment." },
                { "134", "I", "Vaporeon", "Showers", "water", "", "Bubble Jet Pokémon", "88.14", "11.86", "1", "29", "45",
                        "8960", "130", "65", "60", "110", "95", "65", "Water Absorb", "", "", "Hydration", "1", "0.5",
                        "0.5", "2", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0",
                        "Eevee", "", "", "", "", "", "", "", "", "",
                        "When Vaporeon’s fins begin to vibrate, it is a sign that rain will come within a few hours." },
                { "135", "I", "Jolteon", "Thunders", "electric", "", "Lightning Pokémon", "88.14", "11.86", "0.8", "24.5",
                        "45", "8960", "65", "65", "60", "110", "95", "130", "Volt Absorb", "", "", "Quick Feet", "1", "1",
                        "1", "0.5", "1", "1", "1", "1", "2", "0.5", "1", "1", "1", "1", "1", "1", "0.5", "1", "0", "0", "0",
                        "Eevee", "", "", "", "", "", "", "", "", "",
                        "If it is angered or startled, the fur all over its body bristles like sharp needles that pierce foes." },
                { "136", "I", "Flareon", "Booster", "fire", "", "Flame Pokémon", "88.14", "11.86", "0.9", "25", "45",
                        "8960", "65", "130", "60", "95", "110", "65", "Flash Fire", "", "", "Guts", "1", "0.5", "2", "1",
                        "0.5", "0.5", "1", "1", "2", "1", "1", "0.5", "2", "1", "1", "1", "0.5", "0.5", "0", "0", "0",
                        "Eevee", "", "", "", "", "", "", "", "", "",
                        "Once it has stored up enough heat, this Pokémon’s body temperature can reach up to 1,700 degrees Fahrenheit." },
                { "137", "I", "Porygon", "Porygon", "normal", "", "Virtual Pokémon", "", "", "0.8", "36.5", "45", "5120",
                        "65", "60", "70", "85", "75", "40", "Trace", "Download", "", "Analytic", "1", "1", "1", "1", "1",
                        "1", "2", "1", "1", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "0", "0", "Porygon",
                        "Trade with  Upgrade", "Porygon2", "Trade with  Dubious Disc", "Porygon-Z", "", "", "", "", "",
                        "State-of-the-art technology was used to create Porygon. It was the first artificial Pokémon to be created via computer programming." },
                { "138", "I", "Omanyte", "Omnite", "rock", "water", "Spiral Pokémon", "88.14", "11.86", "0.4", "7.5", "45",
                        "7680", "35", "40", "100", "90", "55", "35", "Swift Swim", "Shell Armor", "", "Weak Armor", "0.5",
                        "0.25", "1", "2", "4", "0.5", "2", "0.5", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "0",
                        "0", "0", "Omanyte", "Level ", "Omastar", "", "", "", "", "", "", "",
                        "Because some Omanyte manage to escape after being restored or are released into the wild by people, this species is becoming a problem." },
                { "139", "I", "Omastar", "Omstar", "rock", "water", "Spiral Pokémon", "88.14", "11.86", "1", "35", "45",
                        "7680", "70", "60", "125", "115", "70", "55", "Swift Swim", "Shell Armor", "", "Weak Armor", "0.5",
                        "0.25", "1", "2", "4", "0.5", "2", "0.5", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1", "0",
                        "0", "0", "Omanyte", "Level ", "Omastar", "", "", "", "", "", "", "",
                        "Weighed down by a large and heavy shell, Omastar couldn’t move very fast. Some say it went extinct because it was unable to catch food." },
                { "140", "I", "Kabuto", "Kabuto", "rock", "water", "Shellfish Pokémon", "88.14", "11.86", "0.5", "11.5",
                        "45", "7680", "30", "80", "90", "55", "45", "55", "Swift Swim", "Battle Armor", "", "Weak Armor",
                        "0.5", "0.25", "1", "2", "4", "0.5", "2", "0.5", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1",
                        "0", "0", "0", "Kabuto", "Level ", "Kabutops", "", "", "", "", "", "", "",
                        "This species is almost entirely extinct. Kabuto molt every three days, making their shells harder and harder." },
                { "141", "I", "Kabutops", "Kabutops", "rock", "water", "Shellfish Pokémon", "88.14", "11.86", "1.3", "40.5",
                        "45", "7680", "60", "115", "105", "65", "70", "80", "Swift Swim", "Battle Armor", "", "Weak Armor",
                        "0.5", "0.25", "1", "2", "4", "0.5", "2", "0.5", "2", "0.5", "1", "1", "1", "1", "1", "1", "1", "1",
                        "0", "0", "0", "Kabuto", "Level ", "Kabutops", "", "", "", "", "", "", "",
                        "Kabutops slices its prey apart and sucks out the fluids. The discarded body parts become food for other Pokémon." },
                { "142", "I", "Aerodactyl", "Ptera", "rock", "flying", "Fossil Pokémon", "88.14", "11.86", "1.8", "59",
                        "45", "8960", "80", "105", "65", "60", "75", "130", "Rock Head", "Pressure", "", "Unnerve", "0.5",
                        "0.5", "2", "2", "1", "2", "1", "0.5", "0", "0.5", "1", "0.5", "2", "1", "1", "1", "2", "1", "0",
                        "0", "0", "Aerodactyl", "", "", "", "", "", "", "", "Mega Aerodactyl", "",
                        "This is a ferocious Pokémon from ancient times. Apparently even modern technology is incapable of producing a perfectly restored specimen." },
                { "143", "I", "Snorlax", "Kabigon", "normal", "", "Sleeping Pokémon", "88.14", "11.86", "2.1", "460", "25",
                        "10240", "160", "110", "65", "65", "110", "30", "Immunity", "Thick Fat", "", "Gluttony", "1", "1",
                        "1", "1", "1", "1", "2", "1", "1", "1", "1", "1", "1", "0", "1", "1", "1", "1", "0", "0", "0",
                        "Munchlax", "Level Up with Happiness Value at 220", "Snorlax", "", "", "", "", "Gigantamax Snorlax",
                        "", "",
                        "It is not satisfied unless it eats over 880 pounds of food every day. When it is done eating, it goes promptly to sleep." },
                { "144", "I", "Articuno", "Freezer", "ice", "flying", "Freeze Pokémon", "", "", "1.7", "55.4", "3", "20480",
                        "90", "85", "100", "95", "125", "85", "Pressure", "Competitive (Galarian Form)", "", "Snow Cloak",
                        "1", "2", "1", "2", "0.5", "1", "1", "1", "0", "1", "1", "0.5", "4", "1", "1", "1", "2", "1", "1",
                        "0", "0", "Articuno", "", "", "", "", "", "", "", "", "",
                        "It’s said that this Pokémon’s beautiful blue wings are made of ice. Articuno flies over snowy mountains, its long tail fluttering along behind it." },
                { "145", "I", "Zapdos", "Thunder", "electric", "flying", "Electric Pokémon", "", "", "1.6", "52.6", "3",
                        "20480", "90", "90", "85", "125", "90", "100", "Pressure", "Defiant (Galarian Form)", "", "Static",
                        "1", "1", "1", "1", "0.5", "2", "0.5", "1", "0", "0.5", "1", "0.5", "2", "1", "1", "1", "0.5", "1",
                        "1", "0", "0", "Zapdos", "", "", "", "", "", "", "", "", "",
                        "This Pokémon has complete control over electricity. There are tales of Zapdos nesting in the dark depths of pitch-black thunderclouds." },
                { "146", "I", "Moltres", "Fire", "fire", "flying", "Flame Pokémon", "", "", "2", "60", "3", "20480", "90",
                        "100", "90", "125", "85", "90", "Pressure", "Berserk (Galarian Form)", "", "Flame Body", "1", "0.5",
                        "2", "2", "0.25", "1", "0.5", "1", "0", "1", "1", "0.25", "4", "1", "1", "1", "0.5", "0.5", "1",
                        "0", "0", "Moltres", "", "", "", "", "", "", "", "", "",
                        "It’s one of the legendary bird Pokémon. When Moltres flaps its flaming wings, they glimmer with a dazzling red glow." },
                { "147", "I", "Dratini", "Miniryu", "dragon", "", "Dragon Pokémon", "50.2", "49.8", "1.8", "3.3", "45",
                        "10240", "41", "64", "45", "50", "50", "50", "Shed Skin", "", "", "Marvel Scale", "1", "0.5", "0.5",
                        "0.5", "0.5", "2", "1", "1", "1", "1", "1", "1", "1", "1", "2", "1", "1", "2", "0", "0", "0",
                        "Dratini", "Level ", "Dragonair", "Level ", "Dragonite", "", "", "", "", "",
                        "Dratini dwells near bodies of rapidly flowing water, such as the plunge pools of waterfalls. As it grows, Dratini will shed its skin many times." },
                { "148", "I", "Dragonair", "Hakuryu", "dragon", "", "Dragon Pokémon", "50.2", "49.8", "4", "16.5", "45",
                        "10240", "61", "84", "65", "70", "70", "70", "Shed Skin", "", "", "Marvel Scale", "1", "0.5", "0.5",
                        "0.5", "0.5", "2", "1", "1", "1", "1", "1", "1", "1", "1", "2", "1", "1", "2", "0", "0", "0",
                        "Dratini", "Level ", "Dragonair", "Level ", "Dragonite", "", "", "", "", "",
                        "This Pokémon lives in pristine oceans and lakes. It can control the weather, and it uses this power to fly into the sky, riding on the wind." },
                { "149", "I", "Dragonite", "Kairyu", "dragon", "flying", "Dragon Pokémon", "50.2", "49.8", "2.2", "210",
                        "45", "10240", "91", "134", "95", "100", "100", "80", "Inner Focus", "", "", "Multiscale", "1",
                        "0.5", "0.5", "1", "0.25", "4", "0.5", "1", "0", "1", "1", "0.5", "2", "1", "2", "1", "1", "2", "0",
                        "0", "0", "Dratini", "Level ", "Dragonair", "Level ", "Dragonite", "", "", "", "", "",
                        "It’s a kindhearted Pokémon. If it spots a drowning person or Pokémon, Dragonite simply must help them." },
                { "150", "I", "Mewtwo", "Mewtwo", "psychic", "", "Genetic Pokémon", "", "", "2", "122", "3", "30720", "106",
                        "110", "90", "154", "90", "130", "Pressure", "", "", "Unnerve", "1", "1", "1", "1", "1", "1", "0.5",
                        "1", "1", "1", "0.5", "2", "1", "2", "1", "2", "1", "1", "0", "1", "0", "Mewtwo", "", "", "", "",
                        "", "", "", "Mega Mewtwo X", "Mega Mewtwo Y",
                        "Its DNA is almost the same as Mew’s. However, its size and disposition are vastly different." },
                { "151", "I", "Mew", "Mew", "psychic", "", "New Species Pokémon", "", "", "0.4", "4", "45", "30720", "100",
                        "100", "100", "100", "100", "100", "Synchronize", "", "", "", "1", "1", "1", "1", "1", "1", "0.5",
                        "1", "1", "1", "0.5", "2", "1", "2", "1", "2", "1", "1", "0", "0", "1", "Mew", "", "", "", "", "",
                        "", "", "", "",
                        "When viewed through a microscope, this Pokémon’s short, fine, delicate hair can be seen." }
        };
    
        public static String[] choosePokemon() {
            return pokedex[(int)(Math.random() * pokedex.length + 1)];
        }
    }